# Numpy

In [1]:
import numpy as np     # import numpy

In [3]:
np.__version__         # check version

'1.26.4'

In [4]:
import sys            # check python version
sys.version

'3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]'

# creating Array

In [5]:
Array =np.array([1,2,3,4,5,6,7,8,9,10])             # creating np.array
print(Array)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
print(Array.ndim)

1


In [9]:
Array2 = np.array([[11,12,13,14,15],[16,17,18,19,20]])    #creating 2-D array 
print(Array2)

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [11]:
print(Array2.ndim)

2


In [13]:
Array3 = np.array([[[21,22,23,],[24,25,26]],[[27,28,29],[30,31,32]]])            # create 3 dim array
print(Array3.ndim)

3


In [16]:
ndarray = np.array([100,200,300,400,500],ndmin=5)            # created 5 dim array
print(ndarray)

[[[[[100 200 300 400 500]]]]]


# Arange function

In [17]:
range(5)

range(0, 5)

In [18]:
range(10,20)

range(10, 20)

In [19]:
np.arange(10)         # print within value between 0 to 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
np.arange(-20,10)       # print negative value

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [22]:
np.arange(5.0)     # floating value

array([0., 1., 2., 3., 4.])

In [23]:
np.arange(20,10)         # 1st no < 2nd no

array([], dtype=int32)

In [24]:
np.arange()              # at least 1 argument / parameter required

TypeError: arange() requires stop to be specified.

In [25]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [26]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [27]:
np.arange(40,50,2)

array([40, 42, 44, 46, 48])

In [28]:
np.arange(10,20,30,5)                   # four parameter are not allowed

TypeError: Cannot interpret '5' as a data type

# Zeros Function

In [29]:
np.zeros(5)                # parameter tuning -  Learned automatically during training.

array([0., 0., 0., 0., 0.])

In [32]:
np.zeros((5,5),dtype =int)        # hyper parameter tuning -  Set manually and tuned to improve performance.

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [36]:
var2 = np.zeros((3,3))
type(var2)

numpy.ndarray

In [35]:
var = np.zeros([2,2])
print(var)
type(var)


[[0. 0.]
 [0. 0.]]


numpy.ndarray

In [38]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
n = (2,2)
var3 = np.zeros(n)   # parameter tuning
print(var3)

[[0. 0.]
 [0. 0.]]


In [41]:
n1 = (3,3)
var4 = np.zeros(n1,dtype=int)
print(var4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# ones function

In [43]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [44]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.ones((4,4),dtype=int)       # hyperparamter tuning

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
n4 = (3,3)                 
var6 = np.ones(n4,dtype=int)       
print(var6)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [49]:
np.twos(5)

AttributeError: module 'numpy' has no attribute 'twos'

In [50]:
np.threeos(3,3)

AttributeError: module 'numpy' has no attribute 'threeos'

In [51]:
np.full((5,5,),2)           # full join which element we want

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [52]:
np.full((3,3),9)       

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [53]:
np.eye(4)                        # print identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# range

In [56]:
range(10)

range(0, 10)

In [62]:
v = list(range(10))
v

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [63]:
type(v)

list

In [64]:
for i in v:
    print(i)

0
1
2
3
4
5
6
7
8
9


# Rand function

In [66]:
np.rand(3,2)

AttributeError: module 'numpy' has no attribute 'rand'

In [83]:
np.random.rand(3,2,2)

array([[[0.63458829, 0.57634478],
        [0.48005612, 0.95557246]],

       [[0.38269697, 0.93001061],
        [0.09768508, 0.99321732]],

       [[0.88322482, 0.58957727],
        [0.39275507, 0.42537075]]])

In [68]:
np.random.rand(5)

array([0.2700109 , 0.76570421, 0.9947317 , 0.67271824, 0.26689739])

In [85]:
np.random.rand(5,5)

array([[0.52188321, 0.76090141, 0.37645949, 0.08416628, 0.75039278],
       [0.77764893, 0.28320052, 0.68187395, 0.27036783, 0.13298778],
       [0.74168909, 0.03690021, 0.73069007, 0.54728347, 0.62769942],
       [0.55545334, 0.17730046, 0.99070669, 0.11923192, 0.63700667],
       [0.91262341, 0.33467792, 0.22367611, 0.48349963, 0.34230978]])

In [70]:
np.random.randint(10,20)

10

In [71]:
np.random.randint(5)

1

In [77]:
np.random.randint(10,20,3)

array([11, 11, 16])

In [78]:
np.random.rand(5,5)

array([[0.73575785, 0.594342  , 0.8413231 , 0.07671085, 0.64109239],
       [0.40564242, 0.24684802, 0.35564815, 0.38541942, 0.87126566],
       [0.57151373, 0.97953739, 0.36495427, 0.83512745, 0.22281781],
       [0.95173826, 0.86217206, 0.16382252, 0.01722053, 0.80478329],
       [0.3923341 , 0.22428689, 0.57932848, 0.77457715, 0.75984976]])

In [79]:
np.random.randint(20,50,5)

array([23, 40, 30, 22, 30])

In [81]:
np.random.randint(-20.8,10,5)

array([  4, -18,  -7,   9,  -4])

In [82]:
np.random.randint(10,20,(3,3))

array([[16, 14, 11],
       [16, 15, 18],
       [13, 18, 12]])

In [86]:
np.random.randint(100,200,(4,4))

array([[148, 165, 169, 154],
       [136, 187, 136, 115],
       [127, 136, 128, 193],
       [168, 150, 157, 128]])

In [87]:
np.random.randint(20,25,2)

array([21, 21])

# repshape

In [90]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
np.arange(10,10)

array([], dtype=int32)

In [93]:
np.arange(5,6)

array([5])

In [97]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
new = np.arange(20,29).reshape(3,3)
new

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

# indexing and slicing

In [106]:
new[:]

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [107]:
new[1,1]

24

In [108]:
new[0:3,0:3]

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [110]:
new[0:1,0:3]

array([[20, 21, 22]])

In [111]:
new[0,2]

22

In [ ]:
# variable[start:stop:step]

In [114]:
new[1:2]        # access only row 

array([[23, 24, 25]])

In [115]:
new[:,2]

array([22, 25, 28])

In [116]:
new[0]       # access row

array([20, 21, 22])

In [117]:
new[:,0]       # access column

array([20, 23, 26])

In [118]:
new[-1]

array([26, 27, 28])

In [127]:
new[-1]

array([26, 27, 28])

In [128]:
new

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [129]:
new[2,2]

28

In [133]:
new[0:3]

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [137]:
new[0:2,1:3]

array([[21, 22],
       [24, 25]])

In [138]:
new[0]

array([20, 21, 22])

In [142]:
new[:,2] 

array([22, 25, 28])

In [143]:
new

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [145]:
new[-1,-3]

26

In [146]:
new[0:3]

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [156]:
new[-3:]           

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [158]:
new[::-1]

array([[26, 27, 28],
       [23, 24, 25],
       [20, 21, 22]])

In [159]:
new[-1,-3]

26

In [161]:
print(new.max())            # print max element

28


In [162]:
print(new.min())            # print min element

20


In [163]:
matrix = np.array([10,20,30,40,50,60])
matrix

array([10, 20, 30, 40, 50, 60])

In [165]:
matrix.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [166]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# order , c = row wise ,F = column wise , A = c

In [167]:
mat  = np.array([1,2,3,4,5,6])

In [168]:
mat

array([1, 2, 3, 4, 5, 6])

In [170]:
mat.reshape((2,3),order="C")     # row wise

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
mat.reshape((2,3),order="F")     # column wise

array([[1, 3, 5],
       [2, 4, 6]])

In [172]:
mat.reshape((2,3),order="A")    # row wise

array([[1, 2, 3],
       [4, 5, 6]])